### ISSUE TITLE
금일 담당 과목 목록 가져오기

### ISSUE THREAD

**Issue by Planybirth** [SUVID-18/check_attendance_professor#14]
교수는 각 날짜에 맞게 자신이 가르쳐야 할 과목을 애플리케이션에서 확인할 수 있어야 합니다.

Firestore로부터 해당 정보를 불러오면 과목에 대한 출결 유효시간이나 강의실 변경을 쉽게 하는 데 도움을 줍니다.

---

Firestore로부터 로그인 한 정보의 교수가 해당 날짜에 담당한 과목 목록을 가져오는 기능이 필요합니다.

**Comment by sun30812** [comment]
#12 에 해당되는게 이거지? 겹치는 것 같네

**Comment by Planybirth** [comment]
#14 -> #12의 교수가 가르치는 과목 가져오기 개발로 대체됨.
